print("Name: Jimmy")
print("Birthday: December 23")
print("Age: 2575")
print("Favroite Color: Green")
print("Favorite Food: Fermented Cabbage Heads")
print("Favorite Activity: Eating Baseballs")
print("Jimmy is from the great plains of Azerbaijan.")
print("Jimmy discovered the activity of fermenting cabages one day. He enjoy.")
print("Jimmy enjoys consuming the cabbage with baseballs he gets from mets games.")
